import {
  useCallback,
  useMemo,
  useRef,
  useState,
  type DragEvent,
  type DragEventHandler,
} from 'react';
import type {
  TimelineClipGroupPlacement,
  TimelineEditCommitResult,
  TimelineEditRejectionReason,
  TimelineInteractionGeometry,
  Track,
} from '@techsquidtv/canvas-timeline-core';
import type { RationalTime } from '@techsquidtv/canvas-timeline-utils';
import { toSeconds } from '@techsquidtv/canvas-timeline-utils';
import { useTimeline } from '../core/useTimeline';
import {
  timelineCommandFail,
  timelineCommandOk,
  type TimelineCommandFailureReason,
  type TimelineCommandResult,
} from '../core/timelineCommandResult';

/** External-drop edit operation selected by app chrome or drop context. */
export type TimelineExternalClipDropEditMode = 'insert' | 'overwrite';

/** Metadata applied when an external drop creates a multi-clip group. */
export interface TimelineExternalClipDropGroupOptions {
  /** Optional stable group id. A random id is generated by the engine when omitted. */
  groupId?: string;
  /** Optional visible group label for app chrome. */
  label?: string;
}

/** Context passed to external clip drop callbacks. */
export interface TimelineExternalClipDropContext<DragData, TrackKind = string> {
  /** App-owned drag payload resolved from the native drag event. */
  data: DragData;
  /** Native React drag event for advanced app integrations. */
  event: DragEvent<HTMLElement>;
  /** Native browser data transfer payload. */
  dataTransfer: DataTransfer;
  /** Track currently under the pointer. */
  targetTrack: Track<TrackKind>;
  /** Zero-based index of the target track. */
  targetTrackIndex: number;
  /** Timeline time under the pointer. */
  dropTime: RationalTime;
  /** Timeline seconds under the pointer. */
  dropSeconds: number;
  /** Horizontal pointer position inside the drop surface. */
  viewportX: number;
  /** Vertical pointer position inside the drop surface. */
  viewportY: number;
  /** Edit operation selected for this drop. */
  editMode: TimelineExternalClipDropEditMode;
}

/** Result of an app-owned external drop guard. */
export interface TimelineExternalClipDropGuardResult {
  /** Whether this payload can drop on the resolved target. */
  canDrop: boolean;
  /** Machine-readable failure reason when rejected. */
  reason?: TimelineCommandFailureReason;
  /** Optional human-readable failure detail. */
  message?: string;
}

/** Custom policy for accepting or rejecting an external drop target. */
export type TimelineExternalClipDropGuard<DragData, TrackKind = string> = (
  context: TimelineExternalClipDropContext<DragData, TrackKind>
) => boolean | TimelineExternalClipDropGuardResult;

/** Props spread onto the timeline element that receives native external drops. */
export interface TimelineExternalClipDropRootProps {
  onDragEnter: DragEventHandler<HTMLElement>;
  onDragOver: DragEventHandler<HTMLElement>;
  onDragLeave: DragEventHandler<HTMLElement>;
  onDrop: DragEventHandler<HTMLElement>;
}

/** Options accepted by `useTimelineExternalClipDrop`. */
export interface UseTimelineExternalClipDropOptions<
  DragData,
  TrackKind = string,
> extends TimelineInteractionGeometry {
  /** Optional viewport width used for track hit testing. Defaults to the drop surface width. */
  viewportWidth?: number;
  /** Edit mode for committed drops. Defaults to overwrite. */
  editMode?:
    | TimelineExternalClipDropEditMode
    | ((
        context: Omit<TimelineExternalClipDropContext<DragData, TrackKind>, 'editMode'>
      ) => TimelineExternalClipDropEditMode);
  /** Resolves app-owned drag data from the native drag event. */
  resolveDragData: (event: DragEvent<HTMLElement>) => DragData | null;
  /** Creates one or more clip placements from the resolved drop context. */
  createPlacements: (
    context: TimelineExternalClipDropContext<DragData, TrackKind>
  ) => readonly TimelineClipGroupPlacement[] | null;
  /** Optional app policy for rejecting target tracks before placement creation. */
  canDropOnTrack?: TimelineExternalClipDropGuard<DragData, TrackKind>;
  /** Optional metadata applied when a drop creates a grouped multi-placement edit. */
  group?:
    | TimelineExternalClipDropGroupOptions
    | ((
        context: TimelineExternalClipDropContext<DragData, TrackKind>
      ) => TimelineExternalClipDropGroupOptions | null | undefined);
  /** Whether to resolve magnetic snapping for placed clips. Multi-placement drops share one group delta. Defaults to true. */
  snap?: boolean;
}

/** Result returned by `useTimelineExternalClipDrop`. */
export interface UseTimelineExternalClipDropResult<TrackKind = string> {
  /** Props for the element that should accept native external drops. */
  rootProps: TimelineExternalClipDropRootProps;
  /** Whether an external drag is currently over the drop surface. */
  dragging: boolean;
  /** Track currently under the pointer, including invalid targets. */
  hoveredTrackId: string | null;
  /** Valid target track id currently accepting the payload. */
  targetTrackId: string | null;
  /** Valid target track currently accepting the payload. */
  targetTrack: Track<TrackKind> | null;
  /** Timeline time under the pointer, when a track is resolved. */
  dropTime: RationalTime | null;
  /** Timeline seconds under the pointer, when a track is resolved. */
  dropSeconds: number | null;
  /** Whether the current external payload can be dropped. */
  valid: boolean;
  /** Machine-readable reason for invalid feedback. */
  reason: TimelineCommandFailureReason | null;
  /** Last committed or rejected drop result. */
  lastResult: TimelineCommandResult<TimelineEditCommitResult> | null;
  /** Clears current hover feedback while preserving the last result. */
  clearDropFeedback: () => void;
}

interface ExternalDropFeedback<TrackKind = string> {
  dragging: boolean;
  hoveredTrackId: string | null;
  targetTrackId: string | null;
  targetTrack: Track<TrackKind> | null;
  dropTime: RationalTime | null;
  dropSeconds: number | null;
  valid: boolean;
  reason: TimelineCommandFailureReason | null;
}

interface ResolvedExternalDropContext<DragData, TrackKind = string> {
  context: TimelineExternalClipDropContext<DragData, TrackKind>;
  valid: boolean;
  reason: TimelineCommandFailureReason | null;
  message?: string;
}

function createEmptyExternalDropFeedback<TrackKind>(): ExternalDropFeedback<TrackKind> {
  return {
    dragging: false,
    hoveredTrackId: null,
    targetTrackId: null,
    targetTrack: null,
    dropTime: null,
    dropSeconds: null,
    valid: false,
    reason: null,
  };
}

function toTimelineCommandFailureReason(
  reason: TimelineEditRejectionReason | null
): TimelineCommandFailureReason {
  return reason ?? 'unsupported';
}

function normalizeDropGuardResult(
  result: boolean | TimelineExternalClipDropGuardResult
): TimelineExternalClipDropGuardResult {
  if (typeof result === 'boolean') {
    return { canDrop: result, reason: result ? undefined : 'unsupported' };
  }
  return result;
}

function isLeavingCurrentTarget(event: DragEvent<HTMLElement>) {
  return (
    event.relatedTarget === null ||
    !(event.relatedTarget instanceof Node) ||
    !event.currentTarget.contains(event.relatedTarget)
  );
}

/**
 * Adds native browser drag-and-drop support for app-owned clip data.
 *
 * The hook owns browser event handling, track/time resolution, and local
 * feedback state. Apps own payload parsing and clip placement factories; the
 * engine owns validation, policy, history, grouped edits, and undo/redo.
 *
 * @param options - Drop geometry, app payload callbacks, edit mode, and optional policy.
 * @returns Root props, feedback state, and the last drop command result.
 */
export function useTimelineExternalClipDrop<DragData, TrackKind = string>(
  options: UseTimelineExternalClipDropOptions<DragData, TrackKind>
): UseTimelineExternalClipDropResult<TrackKind> {
  const { engine } = useTimeline();
  const {
    collapsedTrackHeight,
    canDropOnTrack,
    createPlacements,
    editMode: editModeOption,
    edgeThreshold,
    group,
    resolveDragData,
    rulerHeight,
    snap,
    touchEdgeThreshold,
    trackHeight,
    viewportWidth,
  } = options;
  const [feedback, setFeedback] = useState<ExternalDropFeedback<TrackKind>>(() =>
    createEmptyExternalDropFeedback()
  );
  const [lastResult, setLastResult] =
    useState<TimelineCommandResult<TimelineEditCommitResult> | null>(null);
  const snappingPreparedRef = useRef(false);

  const clearDropFeedback = useCallback(() => {
    setFeedback(createEmptyExternalDropFeedback());
    snappingPreparedRef.current = false;
  }, []);

  const prepareDropSnapping = useCallback(() => {
    if (snap === false || snappingPreparedRef.current) {
      return;
    }
    engine.prepareSnapping({ operation: 'custom' });
    snappingPreparedRef.current = true;
  }, [engine, snap]);

  const resolveContext = useCallback(
    (
      event: DragEvent<HTMLElement>
    ): ResolvedExternalDropContext<DragData, TrackKind> | TimelineCommandResult => {
      const data = resolveDragData(event);
      if (data === null) {
        return timelineCommandFail('unsupported');
      }

      const bounds = event.currentTarget.getBoundingClientRect();
      const viewportX = event.clientX - bounds.left;
      const viewportY = event.clientY - bounds.top;
      const target = engine.getTrackAtPoint<TrackKind>({
        collapsedTrackHeight,
        edgeThreshold,
        rulerHeight,
        touchEdgeThreshold,
        trackHeight,
        viewportWidth: viewportWidth ?? bounds.width,
        x: viewportX,
        y: viewportY,
      });

      if (target === null) {
        return timelineCommandFail('invalid-track');
      }
      if (target.track.locked) {
        return timelineCommandFail('locked');
      }

      const dropTime = engine.pixelToTime(viewportX);
      const baseContext = {
        data,
        event,
        dataTransfer: event.dataTransfer,
        targetTrack: target.track,
        targetTrackIndex: target.trackIndex,
        dropTime,
        dropSeconds: toSeconds(dropTime),
        viewportX,
        viewportY,
      };
      const editMode =
        typeof editModeOption === 'function'
          ? editModeOption(baseContext)
          : (editModeOption ?? 'overwrite');
      const context: TimelineExternalClipDropContext<DragData, TrackKind> = {
        ...baseContext,
        editMode,
      };
      const guardResult =
        canDropOnTrack === undefined
          ? { canDrop: true }
          : normalizeDropGuardResult(canDropOnTrack(context));

      return {
        context,
        valid: guardResult.canDrop,
        reason: guardResult.canDrop ? null : (guardResult.reason ?? 'unsupported'),
        ...(guardResult.message !== undefined ? { message: guardResult.message } : {}),
      };
    },
    [
      engine,
      collapsedTrackHeight,
      canDropOnTrack,
      editModeOption,
      edgeThreshold,
      resolveDragData,
      rulerHeight,
      touchEdgeThreshold,
      trackHeight,
      viewportWidth,
    ]
  );

  const publishFeedback = useCallback(
    (resolved: ResolvedExternalDropContext<DragData, TrackKind> | TimelineCommandResult) => {
      if ('context' in resolved) {
        setFeedback({
          dragging: true,
          hoveredTrackId: resolved.context.targetTrack.id,
          targetTrackId: resolved.valid ? resolved.context.targetTrack.id : null,
          targetTrack: resolved.valid ? resolved.context.targetTrack : null,
          dropTime: resolved.context.dropTime,
          dropSeconds: resolved.context.dropSeconds,
          valid: resolved.valid,
          reason: resolved.reason,
        });
        return;
      }

      setFeedback({
        ...createEmptyExternalDropFeedback(),
        dragging: true,
        reason: resolved.reason ?? 'unsupported',
      });
    },
    []
  );

  const commitPlacements = useCallback(
    (
      context: TimelineExternalClipDropContext<DragData, TrackKind>,
      placements: readonly TimelineClipGroupPlacement[]
    ): TimelineCommandResult<TimelineEditCommitResult> => {
      if (placements.length === 0) {
        return timelineCommandFail('unsupported');
      }
      const groupOptions = typeof group === 'function' ? group(context) : group;
      const result = engine.commitEdit(
        placements.length === 1
          ? {
              type: context.editMode,
              clip: placements[0].clip,
              targetTrackId: placements[0].targetTrackId,
              startTime: placements[0].startTime,
              snap,
            }
          : {
              type: context.editMode === 'insert' ? 'insert-clip-group' : 'overwrite-clip-group',
              placements,
              groupId: groupOptions?.groupId,
              label: groupOptions?.label,
              snap,
            }
      );

      return result.committed
        ? timelineCommandOk(result)
        : timelineCommandFail<TimelineEditCommitResult>(
            toTimelineCommandFailureReason(result.preview.reason),
            result.preview.message
          );
    },
    [engine, group, snap]
  );

  const onDragEnter = useCallback<DragEventHandler<HTMLElement>>(
    (event) => {
      prepareDropSnapping();
      publishFeedback(resolveContext(event));
    },
    [prepareDropSnapping, publishFeedback, resolveContext]
  );

  const onDragOver = useCallback<DragEventHandler<HTMLElement>>(
    (event) => {
      prepareDropSnapping();
      const resolved = resolveContext(event);
      publishFeedback(resolved);
      event.preventDefault();
      event.dataTransfer.dropEffect = 'context' in resolved && resolved.valid ? 'copy' : 'none';
    },
    [prepareDropSnapping, publishFeedback, resolveContext]
  );

  const onDragLeave = useCallback<DragEventHandler<HTMLElement>>(
    (event) => {
      if (isLeavingCurrentTarget(event)) {
        clearDropFeedback();
      }
    },
    [clearDropFeedback]
  );

  const onDrop = useCallback<DragEventHandler<HTMLElement>>(
    (event) => {
      event.preventDefault();
      prepareDropSnapping();
      const resolved = resolveContext(event);
      if (!('context' in resolved) || !resolved.valid) {
        const result = timelineCommandFail<TimelineEditCommitResult>(
          resolved.reason ?? 'unsupported',
          resolved.message
        );
        setLastResult(result);
        clearDropFeedback();
        return;
      }

      const placements = createPlacements(resolved.context);
      const result =
        placements === null
          ? timelineCommandFail<TimelineEditCommitResult>('unsupported')
          : commitPlacements(resolved.context, placements);
      setLastResult(result);
      clearDropFeedback();
    },
    [clearDropFeedback, commitPlacements, createPlacements, prepareDropSnapping, resolveContext]
  );

  const rootProps = useMemo(
    () => ({
      onDragEnter,
      onDragOver,
      onDragLeave,
      onDrop,
    }),
    [onDragEnter, onDragLeave, onDragOver, onDrop]
  );

  return {
    rootProps,
    ...feedback,
    lastResult,
    clearDropFeedback,
  };
}
