packages:
  - 'apps/*'
  - 'packages/*'
  - 'scripts'
onlyBuiltDependencies:
  - esbuild
  - sharp
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vitest: 4.1.10
  vite-plus: 0.2.4
  '@vitest/coverage-v8': 4.1.10
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.2'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.2'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.2'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.2'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.2'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.2'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.2'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.2'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.2'
  - vite-plus@0.2.2
  - '@astrojs/cloudflare@14.1.1'
  - '@astrojs/internal-helpers@0.10.1'
  - '@astrojs/markdown-remark@7.2.1'
  - '@astrojs/markdown-satteri@0.3.3'
  - '@astrojs/mdx@7.0.2'
  - '@astrojs/react@6.0.1'
  - astro@7.0.6
  - '@cloudflare/workerd-darwin-64@1.20260702.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260702.1'
  - '@cloudflare/workerd-linux-64@1.20260702.1'
  - '@cloudflare/workerd-linux-arm64@1.20260702.1'
  - '@cloudflare/workerd-windows-64@1.20260702.1'
  - miniflare@4.20260701.0
  - workerd@1.20260702.1
  - wrangler@4.107.0
