import react from '@vitejs/plugin-react';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, lazyPlugins } from 'vite-plus';

const workspaceRoot = fileURLToPath(new URL('.', import.meta.url));
const packageWorkspaceFilter = '--filter "./packages/*" --fail-if-no-match';
const publishablePackageNames = [
  'utils',
  'core',
  'react',
  'renderer',
  'html-media-adapter',
  'mediabunny-adapter',
  'timeline',
] as const;
const packageBuildInput = (packageName: (typeof publishablePackageNames)[number]) => [
  `packages/${packageName}/src/**`,
  `!packages/${packageName}/src/**/*.test.ts`,
  `!packages/${packageName}/src/**/*.test.tsx`,
  `packages/${packageName}/package.json`,
  `packages/${packageName}/tsconfig.json`,
  `packages/${packageName}/vite.config.ts`,
  'package.json',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  'scripts/**',
  'tsconfig.base.json',
  'tsconfig.check.base.json',
];
const packageBuildTask = (
  packageName: (typeof publishablePackageNames)[number],
  command = 'vp pack'
) => ({
  command,
  cwd: `packages/${packageName}`,
  input: packageBuildInput(packageName),
  output: [`packages/${packageName}/dist/**`],
});
const packageBuildTaskName = (packageName: (typeof publishablePackageNames)[number]) =>
  `build:${packageName}`;

export default defineConfig({
  plugins: lazyPlugins(() => [react()]),
  resolve: {
    alias: [
      {
        find: /^#full-editor\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'apps/full-editor-demo/src/$1'),
      },
      {
        find: /^#core\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/core/src/$1'),
      },
      {
        find: /^#html-media-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/html-media-adapter/src/$1'),
      },
      {
        find: /^#mediabunny-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/mediabunny-adapter/src/$1'),
      },
      {
        find: /^#react\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/$1'),
      },
      {
        find: /^#renderer\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/renderer/src/$1'),
      },
      {
        find: /^#test-utils\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'test-utils/$1'),
      },
      {
        find: /^#timeline\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/timeline/src/$1'),
      },
      {
        find: /^#utils\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/utils/src/$1'),
      },
      {
        find: /^#www\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'apps/www/src/$1'),
      },
      {
        find: /^#www-generated\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'apps/www/.generated/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-core$/,
        replacement: path.resolve(workspaceRoot, 'packages/core/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-core\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/core/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/range-scrollbar$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/rangeScrollbar/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/timecode-field$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/timecodeField/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/timecode-input$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/timecodeInput/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-html-media-adapter$/,
        replacement: path.resolve(workspaceRoot, 'packages/html-media-adapter/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-html-media-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/html-media-adapter/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-mediabunny-adapter$/,
        replacement: path.resolve(workspaceRoot, 'packages/mediabunny-adapter/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-mediabunny-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/mediabunny-adapter/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-renderer$/,
        replacement: path.resolve(workspaceRoot, 'packages/renderer/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-renderer\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/renderer/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-utils$/,
        replacement: path.resolve(workspaceRoot, 'packages/utils/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-utils\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/utils/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline$/,
        replacement: path.resolve(workspaceRoot, 'packages/timeline/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/timeline/src/$1'),
      },
    ],
  },
  staged: {
    '*.{js,jsx,ts,tsx,mjs,cjs}': ['vp lint --fix', 'vp fmt'],
    '*.{json,md,mdx,yml,yaml,css}': 'vp fmt',
  },
  run: {
    tasks: {
      'build:core': {
        ...packageBuildTask('core'),
        dependsOn: ['build:utils'],
      },
      'build:html-media-adapter': {
        ...packageBuildTask('html-media-adapter'),
        dependsOn: ['build:core', 'build:react', 'build:utils'],
      },
      'build:mediabunny-adapter': {
        ...packageBuildTask('mediabunny-adapter'),
        dependsOn: ['build:core', 'build:react', 'build:utils'],
      },
      'build:full-editor-demo': {
        command: 'vp build',
        cwd: 'apps/full-editor-demo',
        input: [
          'apps/full-editor-demo/index.html',
          'apps/full-editor-demo/package.json',
          'apps/full-editor-demo/src/**',
          'apps/full-editor-demo/tsconfig.json',
          'apps/full-editor-demo/vite.config.ts',
          'package.json',
          'packages/core/src/**',
          'packages/mediabunny-adapter/src/**',
          'packages/react/src/**',
          'packages/renderer/src/**',
          'packages/utils/src/**',
          'pnpm-lock.yaml',
          'tsconfig*.json',
        ],
        output: ['apps/full-editor-demo/dist/**'],
      },
      'build:packages': {
        command: 'node -e ""',
        cache: false,
        dependsOn: publishablePackageNames.map(packageBuildTaskName),
      },
      'build:react': {
        ...packageBuildTask(
          'react',
          'vp pack && cp src/base.css dist/base.css && cp src/theme.css dist/theme.css && cp src/styles.css dist/styles.css'
        ),
        dependsOn: ['build:core', 'build:utils'],
      },
      'build:renderer': {
        ...packageBuildTask('renderer'),
        dependsOn: ['build:core', 'build:react', 'build:utils'],
      },
      'build:timeline': {
        ...packageBuildTask(
          'timeline',
          'vp pack && cp src/base.css dist/base.css && cp src/theme.css dist/theme.css && cp src/styles.css dist/styles.css'
        ),
        dependsOn: [
          'build:core',
          'build:html-media-adapter',
          'build:react',
          'build:renderer',
          'build:utils',
        ],
      },
      'build:utils': packageBuildTask('utils'),
      'build:www': {
        command: 'node -e ""',
        cache: false,
        dependsOn: ['build:www:astro'],
      },
      'build:www:astro': {
        command: 'vp exec astro build',
        cache: false,
        cwd: 'apps/www',
        dependsOn: [
          'docs:sponsors',
          'docs:api',
          'docs:demos',
          'docs:links',
          'docs:registry',
          'docs:og',
          'docs:editor',
        ],
      },
      'coverage:package': {
        command: 'node scripts/check-package-coverage.mjs',
        input: ['coverage/coverage-final.json', 'scripts/check-package-coverage.mjs'],
        output: [],
      },
      'custom:rules': {
        command: 'node scripts/check-vite-plus-custom-rules.mjs',
        input: [
          '.github/**',
          'apps/www/src/**/*.astro',
          'apps/www/src/**/*.mdx',
          'package.json',
          'packages/core/package.json',
          'packages/core/src/**',
          'packages/react/package.json',
          'packages/react/src/**',
          'scripts/check-vite-plus-custom-rules.mjs',
          'tools/**',
          'tsconfig*.json',
        ],
        output: [],
      },
      'repo:dev:www': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www dev',
        cache: false,
      },
      'repo:dev:editor': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-full-editor-demo dev',
        cache: false,
      },
      'repo:build': ['vp run build:packages', 'vp run build:www'],
      ci: ['vp run ci:quality', 'vp run repo:build', 'vp run repo:package:validate'],
      'ci:quality': [
        'vp run knip',
        'vp run docs:registry',
        'vp run repo:typecheck',
        'vp run repo:check',
        'vp run custom:rules',
        'vp run test:coverage',
        'vp run coverage:package',
      ],
      'repo:check': {
        command: 'node -e ""',
        cache: false,
        dependsOn: ['source:check', 'docs:links'],
      },
      'repo:clean': {
        command: 'vp run -r clean',
        cache: false,
      },
      'repo:dev': {
        command: ['vp run build:packages', 'vp run --filter @techsquidtv/canvas-timeline-www dev'],
        cache: false,
      },
      'docs:api': {
        command: 'node scripts/generate-api-reference.mjs',
        cwd: 'apps/www',
        input: [
          'apps/www/package.json',
          'apps/www/scripts/generate-api-reference.mjs',
          'package.json',
          'packages/*/package.json',
          'packages/*/src/**',
          'pnpm-lock.yaml',
          'tsconfig*.json',
        ],
        output: [
          'apps/www/.generated/api-reference.json',
          'apps/www/.generated/api-reference-warnings.txt',
        ],
      },
      'docs:demos': {
        command: 'node scripts/verify-demos.mjs',
        cwd: 'apps/www',
        input: [
          'apps/www/scripts/verify-demos.mjs',
          'apps/www/src/data/demo-code.ts',
          'apps/www/src/data/demo-components.ts',
          'apps/www/src/data/demos.ts',
          'apps/www/src/demos/**',
        ],
        output: [],
      },
      'docs:editor': {
        command: 'node scripts/stage-full-editor-demo.mjs',
        cwd: 'apps/www',
        dependsOn: ['build:full-editor-demo'],
        input: ['apps/full-editor-demo/dist/**', 'apps/www/scripts/stage-full-editor-demo.mjs'],
        output: [
          'apps/www/public/demos/full-editor-demo/**',
          'apps/www/public/full-editor-demo/**',
        ],
      },
      'docs:links': {
        command: 'node scripts/verify-links.mjs',
        cwd: 'apps/www',
        dependsOn: ['docs:api'],
        input: [
          'apps/www/.generated/api-reference.json',
          'apps/www/public/demo-media/**',
          'apps/www/public/favicon.svg',
          'apps/www/public/logo.svg',
          'apps/www/scripts/verify-links.mjs',
          'apps/www/src/**/*.astro',
          'apps/www/src/content/**',
          'apps/www/src/data/**',
          'apps/www/src/pages/**',
        ],
        output: [],
      },
      'docs:og': {
        command: 'tsx scripts/generate-open-graph.ts',
        cwd: 'apps/www',
        dependsOn: ['docs:api', 'docs:registry'],
        input: [
          'apps/www/package.json',
          'apps/www/public/logo.svg',
          'apps/www/scripts/generate-open-graph.ts',
          'apps/www/src/assets/og-background.webp',
          'apps/www/src/content/**',
          'apps/www/src/data/**',
          'apps/www/src/lib/api-reference.ts',
          'apps/www/src/lib/open-graph-pages.ts',
          'apps/www/src/lib/open-graph.ts',
          'package.json',
        ],
        output: ['apps/www/public/open-graph/**'],
      },
      'docs:registry': {
        command: 'node scripts/verify-react-registry.mjs',
        input: [
          'apps/www/src/data/react-hook-metadata.ts',
          'apps/www/src/data/react-registry.ts',
          'package.json',
          'packages/react/package.json',
          'packages/react/src/**',
          'scripts/verify-react-registry.mjs',
          'tsconfig*.json',
        ],
        output: ['apps/www/.generated/react-registry-snippets/**'],
      },
      'docs:sponsors': {
        command: 'vp exec tsx scripts/sync-sponsors.ts',
        cache: false,
        cwd: 'apps/www',
      },
      knip: {
        command: 'knip',
        input: [
          '.github/**',
          'apps/*/package.json',
          'apps/*/src/**',
          'apps/www/scripts/**',
          'knip.json',
          'package.json',
          'packages/*/package.json',
          'packages/*/src/**',
          'scripts/**',
          'tools/**',
          'tsconfig*.json',
          'vite.config.ts',
        ],
        output: [],
      },
      'repo:package:check': [
        `vp run ${packageWorkspaceFilter} clean`,
        'vp run build:packages',
        'vp run repo:package:validate',
      ],
      'repo:package:validate': [
        'node scripts/check-publishable-packages.mjs',
        'node scripts/check-consumer-smoke.mjs',
      ],
      'repo:preview': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www preview',
        cache: false,
      },
      'repo:preview:www': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www preview',
        cache: false,
      },
      'release:publish': ['vp run repo:package:check', 'vp exec changeset publish'],
      'repo:typecheck': {
        command: 'tsc -b',
        input: [
          'apps/*/src/**',
          'apps/*/tsconfig.json',
          'package.json',
          'packages/*/src/**',
          'packages/*/tsconfig.json',
          'tsconfig*.json',
        ],
        output: [],
      },
      'source:check': {
        command: 'vp check',
        input: [
          '.github/**',
          '*.json',
          '*.md',
          'apps/*/*.config.ts',
          'apps/*/package.json',
          'apps/*/src/**',
          'apps/*/tsconfig.json',
          'apps/*/vite.config.ts',
          'package.json',
          'packages/*/package.json',
          'packages/*/src/**',
          'scripts/**',
          'test-utils/**',
          'tools/**',
          'tsconfig*.json',
          'vite.config.ts',
        ],
        output: [],
      },
      'test:coverage': {
        command: 'vp test run --coverage',
        input: [
          'apps/*/src/**',
          'apps/*/vite.config.ts',
          'package.json',
          'packages/*/src/**',
          'packages/*/vite.config.ts',
          'test-utils/**',
          'tsconfig*.json',
          'vite.config.ts',
        ],
        output: ['coverage/**'],
      },
    },
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react'],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      '**/dist',
      '**/dist/**/*',
      'node_modules',
      'coverage',
      '**/.astro',
      '**/.generated',
      '**/.wrangler',
      '**/.wrangler/**/*',
      '**/*.astro',
      'package-lock.json',
      'pnpm-lock.yaml',
      'server.js',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.mjs'],
        globals: {
          console: 'readonly',
          process: 'readonly',
        },
      },
      {
        files: ['**/*.{ts,tsx}'],
        rules: {
          'react/display-name': 'error',
          'react/jsx-key': 'error',
          'react/jsx-no-comment-textnodes': 'error',
          'react/jsx-no-duplicate-props': 'error',
          'react/jsx-no-target-blank': 'error',
          'react/jsx-no-undef': 'error',
          'react/no-children-prop': 'error',
          'react/no-danger-with-children': 'error',
          'react/no-direct-mutation-state': 'error',
          'react/no-find-dom-node': 'error',
          'react/no-is-mounted': 'error',
          'react/no-render-return-value': 'error',
          'react/no-string-refs': 'error',
          'react/no-unescaped-entities': 'error',
          'react/no-unknown-property': 'error',
          'react/no-unsafe': 'off',
          'react/react-in-jsx-scope': 'off',
          'react/require-render-return': 'error',
          'react/no-array-index-key': 'error',
          'react/no-unstable-nested-components': 'error',
          'react/self-closing-comp': 'error',
          eqeqeq: ['error', 'always'],
          curly: ['error', 'all'],
          'no-undef': 'off',
          'no-console': [
            'warn',
            {
              allow: ['warn', 'error', 'info'],
            },
          ],
          'no-duplicate-imports': [
            'error',
            {
              allowSeparateTypeImports: true,
            },
          ],
          'no-unused-vars': [
            'error',
            {
              argsIgnorePattern: '^_',
              varsIgnorePattern: '^_',
            },
          ],
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'error',
          'react/only-export-components': [
            'error',
            {
              allowConstantExport: true,
            },
          ],
          'canvas-timeline/max-exports-per-module': [
            'error',
            {
              maxImplementationExports: 15,
              maxDomainBarrelExports: 30,
              maxRootBarrelDirectExports: 12,
              allowFiles: [
                'packages/core/src/events.ts',
                'packages/core/src/types.ts',
                'packages/react/src/components/index.ts',
                'packages/react/src/docs-metadata.ts',
                'packages/react/src/hooks/docs/docsMetadata.ts',
                'packages/react/src/rangeScrollbar/RangeScrollbar.tsx',
              ],
            },
          ],
          'canvas-timeline/react-api-tsdoc': 'error',
          'canvas-timeline/no-relative-imports': 'error',
          'typescript/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': 'allow-with-description',
              'ts-ignore': true,
              'ts-nocheck': true,
              'ts-check': false,
              minimumDescriptionLength: 12,
            },
          ],
          'typescript/consistent-type-imports': [
            'error',
            {
              fixStyle: 'separate-type-imports',
              prefer: 'type-imports',
            },
          ],
          'typescript/no-import-type-side-effects': 'error',
          'typescript/no-non-null-assertion': 'error',
          'typescript/explicit-module-boundary-types': 'off',
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
      {
        name: 'canvas-timeline',
        specifier: './tools/oxlint-plugin-canvas-timeline.mjs',
      },
    ],
  },
  fmt: {
    semi: true,
    trailingComma: 'es5',
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    endOfLine: 'lf',
    sortPackageJson: false,
    ignorePatterns: ['**/.wrangler', '**/.wrangler/**/*'],
  },
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['apps/**/*.{test,spec}.{ts,tsx}', 'packages/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['apps/**/*.{ts,tsx}', 'packages/**/*.{ts,tsx}'],
      exclude: [
        'apps/**/.generated/**',
        'apps/**/vite-env.d.ts',
        'apps/**/src/components/**/*.{ts,tsx}',
        'apps/**/src/data/blog.ts',
        'apps/**/src/data/*.generated.ts',
        'apps/**/src/data/react-registry.ts',
        'apps/**/src/pages/**/*.{ts,tsx}',
        '**/*.test.{ts,tsx}',
        'packages/renderer/src/worker.ts',
      ],
      thresholds: {
        lines: 60,
        functions: 60,
        branches: 50,
        statements: 60,
      },
    },
  },
});
