import react from '@vitejs/plugin-react';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, lazyPlugins } from 'vite-plus';

const workspaceRoot = fileURLToPath(new URL('.', import.meta.url));
const packageWorkspaceFilter = '--filter "./packages/*" --fail-if-no-match';

export default defineConfig({
  plugins: lazyPlugins(() => [react()]),
  resolve: {
    alias: [
      {
        find: /^@techsquidtv\/canvas-timeline-core$/,
        replacement: path.resolve(workspaceRoot, 'packages/core/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-core\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/core/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/range-scrollbar$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/rangeScrollbar/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/timecode-field$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/timecodeField/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/timecode-input$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/timecodeInput/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-react\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/react/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-html-media-adapter$/,
        replacement: path.resolve(workspaceRoot, 'packages/html-media-adapter/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-html-media-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/html-media-adapter/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-mediabunny-adapter$/,
        replacement: path.resolve(workspaceRoot, 'packages/mediabunny-adapter/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-mediabunny-adapter\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/mediabunny-adapter/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-renderer$/,
        replacement: path.resolve(workspaceRoot, 'packages/renderer/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-renderer\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/renderer/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-utils$/,
        replacement: path.resolve(workspaceRoot, 'packages/utils/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline-utils\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/utils/src/$1'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline$/,
        replacement: path.resolve(workspaceRoot, 'packages/timeline/src/index.ts'),
      },
      {
        find: /^@techsquidtv\/canvas-timeline\/(.*)$/,
        replacement: path.resolve(workspaceRoot, 'packages/timeline/src/$1'),
      },
    ],
  },
  staged: {
    '*.{js,jsx,ts,tsx,mjs,cjs}': ['vp lint --fix', 'vp fmt'],
    '*.{json,md,mdx,yml,yaml,css}': 'vp fmt',
  },
  run: {
    tasks: {
      'build:packages': `vp run --cache ${packageWorkspaceFilter} build`,
      'build:www': 'vp run --filter @techsquidtv/canvas-timeline-www build',
      'custom:rules': 'node scripts/check-vite-plus-custom-rules.mjs',
      'repo:dev:www': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www dev',
        cache: false,
      },
      'repo:dev:editor': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-full-editor-demo dev',
        cache: false,
      },
      'repo:build': [
        'vp run build:packages',
        'vp run --filter @techsquidtv/canvas-timeline-www build',
      ],
      ci: [
        'knip',
        'vp run --filter @techsquidtv/canvas-timeline-www docs:registry',
        'vp run repo:typecheck',
        'vp run repo:check',
        'vp run custom:rules',
        'vp test run --coverage',
        'node scripts/check-package-coverage.mjs',
      ],
      'repo:check': [
        'vp check',
        'vp run docs:api',
        'vp run --filter @techsquidtv/canvas-timeline-www docs:links',
      ],
      'repo:clean': {
        command: 'vp run -r clean',
        cache: false,
      },
      'repo:dev': {
        command: ['vp run build:packages', 'vp run --filter @techsquidtv/canvas-timeline-www dev'],
        cache: false,
      },
      'docs:api': 'vp run --filter @techsquidtv/canvas-timeline-www docs:api',
      knip: 'knip',
      'repo:package:check': [
        'vp run build:packages',
        'node scripts/check-publishable-packages.mjs',
        'node scripts/check-consumer-smoke.mjs',
      ],
      'repo:preview': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www preview',
        cache: false,
      },
      'repo:preview:www': {
        command: 'vp run --filter @techsquidtv/canvas-timeline-www preview',
        cache: false,
      },
      'release:publish': ['vp run repo:package:check', 'vp exec changeset publish'],
      'repo:typecheck': 'vp exec tsc -b',
    },
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react'],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      '**/dist',
      '**/dist/**/*',
      'node_modules',
      'coverage',
      '**/.astro',
      '**/.generated',
      '**/.wrangler',
      '**/.wrangler/**/*',
      '**/*.astro',
      'package-lock.json',
      'pnpm-lock.yaml',
      'server.js',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.mjs'],
        globals: {
          console: 'readonly',
          process: 'readonly',
        },
      },
      {
        files: ['**/*.{ts,tsx}'],
        rules: {
          'react/display-name': 'error',
          'react/jsx-key': 'error',
          'react/jsx-no-comment-textnodes': 'error',
          'react/jsx-no-duplicate-props': 'error',
          'react/jsx-no-target-blank': 'error',
          'react/jsx-no-undef': 'error',
          'react/no-children-prop': 'error',
          'react/no-danger-with-children': 'error',
          'react/no-direct-mutation-state': 'error',
          'react/no-find-dom-node': 'error',
          'react/no-is-mounted': 'error',
          'react/no-render-return-value': 'error',
          'react/no-string-refs': 'error',
          'react/no-unescaped-entities': 'error',
          'react/no-unknown-property': 'error',
          'react/no-unsafe': 'off',
          'react/react-in-jsx-scope': 'off',
          'react/require-render-return': 'error',
          'react/no-array-index-key': 'error',
          'react/no-unstable-nested-components': 'error',
          'react/self-closing-comp': 'error',
          eqeqeq: ['error', 'always'],
          curly: ['error', 'all'],
          'no-undef': 'off',
          'no-console': [
            'warn',
            {
              allow: ['warn', 'error', 'info'],
            },
          ],
          'no-duplicate-imports': [
            'error',
            {
              allowSeparateTypeImports: true,
            },
          ],
          'no-unused-vars': [
            'error',
            {
              argsIgnorePattern: '^_',
              varsIgnorePattern: '^_',
            },
          ],
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'error',
          'react/only-export-components': [
            'error',
            {
              allowConstantExport: true,
            },
          ],
          'canvas-timeline/max-exports-per-module': [
            'error',
            {
              maxImplementationExports: 15,
              maxDomainBarrelExports: 30,
              maxRootBarrelDirectExports: 12,
              allowFiles: [
                'packages/core/src/events.ts',
                'packages/core/src/types.ts',
                'packages/react/src/components/index.ts',
                'packages/react/src/docs-metadata.ts',
                'packages/react/src/hooks/docs/docsMetadata.ts',
                'packages/react/src/rangeScrollbar/RangeScrollbar.tsx',
              ],
            },
          ],
          'canvas-timeline/react-api-tsdoc': 'error',
          'typescript/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': 'allow-with-description',
              'ts-ignore': true,
              'ts-nocheck': true,
              'ts-check': false,
              minimumDescriptionLength: 12,
            },
          ],
          'typescript/consistent-type-imports': [
            'error',
            {
              fixStyle: 'separate-type-imports',
              prefer: 'type-imports',
            },
          ],
          'typescript/no-import-type-side-effects': 'error',
          'typescript/no-non-null-assertion': 'error',
          'typescript/explicit-module-boundary-types': 'off',
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
      {
        name: 'canvas-timeline',
        specifier: './tools/oxlint-plugin-canvas-timeline.mjs',
      },
    ],
  },
  fmt: {
    semi: true,
    trailingComma: 'es5',
    singleQuote: true,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    endOfLine: 'lf',
    sortPackageJson: false,
    ignorePatterns: ['**/.wrangler', '**/.wrangler/**/*'],
  },
  test: {
    environment: 'jsdom',
    globals: true,
    include: ['apps/**/*.{test,spec}.{ts,tsx}', 'packages/**/*.{test,spec}.{ts,tsx}'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      include: ['apps/**/*.{ts,tsx}', 'packages/**/*.{ts,tsx}'],
      exclude: [
        'apps/**/.generated/**',
        'apps/**/vite-env.d.ts',
        'apps/**/src/components/**/*.{ts,tsx}',
        'apps/**/src/data/blog.ts',
        'apps/**/src/data/*.generated.ts',
        'apps/**/src/data/react-registry.ts',
        'apps/**/src/pages/**/*.{ts,tsx}',
        '**/*.test.{ts,tsx}',
        'packages/renderer/src/worker.ts',
      ],
      thresholds: {
        lines: 60,
        functions: 60,
        branches: 50,
        statements: 60,
      },
    },
  },
});
